### PR TITLE
Custom parsedown class for extensions

### PR DESCRIPTION
**Pull request by DevDavido**
Hello 👋 !
I started to use your package and it's useful in several of my projects, thanks for that!
There's one project where I need to make use of [Parsedowns extension possibility](https://github.com/erusev/parsedown/wiki/Tutorial:-Create-Extensions),
that's why I propose this PR and hope it could get merged.

Cheers,
David

### CODE REVIEW

**Comment by DevDavido** [comment]
The last remaining Nitpick-CI message isn't correct.

**Comment by eagostini** [comment]
Hi @DevDavido, thank you for your merge request and for the kind words. Before I can proceed, I have I few things I would like to understand first. How do you manage to extend **Parsedown** currently when using this package in your projects? I reckon there's an improvement for your implementation if this is the right way to go.

**Comment by DevDavido** [comment]
> How do you manage to extend **Parsedown** currently when using this package in your projects?

I set the FQN for the extended Parsedown class in the [`src/Support/parsedown.php`](https://github.com/DevDavido/laravel/blob/custom-parsedown-class/src/Support/parsedown.php). By default it is the original Parsedown class. If another class is used, it'll check (75fb15ab6b5b0b13862c1c10869ac417139833ba) if it's extended by Parsedown.

**Comment by eagostini** [comment]
> > How do you manage to extend **Parsedown** currently when using this package in your projects?
> 
> I set the FQN for the extended Parsedown class in the [`src/Support/parsedown.php`](https://github.com/DevDavido/laravel/blob/custom-parsedown-class/src/Support/parsedown.php). By default it is the original Parsedown class. If another class is used, it'll check ([75fb15a](https://github.com/parsedown/laravel/commit/75fb15ab6b5b0b13862c1c10869ac417139833ba)) if it's extended by Parsedown.

I understand this is what your proposal is meant to do, but how do you work this around if this proposal of yours is not yet in place? What your current implementation for extending **Parsedown** looks like?

**Comment by DevDavido** [comment]
That's individual for every user? My PR provides the possibility to use an Parsedown extended class just like in the official example:
https://github.com/erusev/parsedown/wiki/Tutorial:-Create-Extensions#add-inline-element

In my special case I set `parsedown_class` in `src/Support/parsedown.php` to `\App\Components\Parsedown::class` with this content:
```php
<?php

namespace App\Components;

use Parsedown as BaseParsedown;

class Parsedown extends BaseParsedown
{
    /**
     * Constructor with new inline types.
     *
     * @return void
     */
    public function __construct()
    {
        $this->InlineTypes['['][] = 'InformationText';
    }

    /**
     * Parses inline information text.
     *
     * @param array $excerpt
     * @return array|void
     */
    protected function inlineInformationText($excerpt)
    {
        // More custom code
    }
}
```

**Comment by DevDavido** [comment]
That's individual for every user? My PR provides the possibility to use an Parsedown extended class (not providing a custom extension itself) just like in the official example:
https://github.com/erusev/parsedown/wiki/Tutorial:-Create-Extensions#add-inline-element

In my special case I set `parsedown_class` in `src/Support/parsedown.php` to `\App\Components\Parsedown::class` with this content:
```php
<?php

namespace App\Components;

use Parsedown as BaseParsedown;

class Parsedown extends BaseParsedown
{
    /**
     * Constructor with new inline types.
     *
     * @return void
     */
    public function __construct()
    {
        $this->InlineTypes['['][] = 'InformationText';
    }

    /**
     * Parses inline information text.
     *
     * @param array $excerpt
     * @return array|void
     */
    protected function inlineInformationText($excerpt)
    {
        // More custom code
    }
}
```

**Comment by eagostini** [comment]
> That's individual for every user? My PR provides the possibility to use an Parsedown extended class (not providing a custom extension itself) just like in the official example:
> https://github.com/erusev/parsedown/wiki/Tutorial:-Create-Extensions#add-inline-element
> 
> In my special case I set `parsedown_class` in `src/Support/parsedown.php` to `\App\Components\Parsedown::class` with this content:
> 
> ```
> <?php
> 
> namespace App\Components;
> 
> use Parsedown as BaseParsedown;
> 
> class Parsedown extends BaseParsedown
> {
>     /**
>      * Constructor with new inline types.
>      *
>      * @return void
>      */
>     public function __construct()
>     {
>         $this->InlineTypes['['][] = 'InformationText';
>     }
> 
>     /**
>      * Parses inline information text.
>      *
>      * @param array $excerpt
>      * @return array|void
>      */
>     protected function inlineInformationText($excerpt)
>     {
>         // More custom code
>     }
> }
> ```

Thank you for sharing your case with me. I understand you're not proposing an extended class but the possibility to extend it only. I am not convinced though that it's required to change the package. You can elegantly achieve the same by adding the following code in a service provider to replace the base implementation that **Parsedown** uses:

```php
<?php

namespace App\Providers;

use App\Components\Parsedown;
use Illuminate\Support\ServiceProvider;

/**
 * Class AppServiceProvider
 * @package App\Providers
 */
class AppServiceProvider extends ServiceProvider
{
    /**
     * @return void
     */
    public function register()
    {
        $this->app->singleton('parsedown', function () {
            return Parsedown::instance();
        });
    }
}
```

By replacing the `parsedown` container during the registering process you can tell **Laravel** which factory you want to use with that service. Please, tell me if that is of use to you.

**Comment by DevDavido** [comment]
Yes, using an own singleton container would be an even more elegant way. Thanks for your suggestion! :)

**Comment by eagostini** [comment]
😉

**Pull request closed without merging**
